### PR TITLE
Complete Accuracy Controller with Unit Test

### PR DESCRIPTION
**Pull request by alexv-anderson**

### CODE REVIEW

**Comment by alexv-anderson** [comment]
@bcroden how can all of the tests pass when I push [#151](https://travis-ci.org/bcroden/QuizDeck-Server/builds/110977294), but not when I merge [#152](https://travis-ci.org/bcroden/QuizDeck-Server/builds/110979340) if there are no conflicts? Does Travis treat a push differently than a merge?

**Comment by alexv-anderson** [comment]
@bcroden do you know why the tests pass when I pushed [#151](https://travis-ci.org/bcroden/QuizDeck-Server/builds/110977294) and failed when I tried to merge [#152](https://travis-ci.org/bcroden/QuizDeck-Server/builds/110979340)? I can't think of why this would happen since there are no merge conflicts.

**Comment by bcroden** [comment]
@alexv-anderson Do you have any unit tests which are dependent on new Date's? With the shared cpu on Travis, the tests generally take longer to run then on our local machines. So sometimes if you make 2 new Dates in a test one will be slightly after the other and they no longer are equal.

**Comment by alexv-anderson** [comment]
No. None of the unit tests that I have are dependent on `Date`s. I use a `long` in `Guess` objects to store a time stamp, but this is only to sort them in the order in which they were received. The `long`s are not used in the `equals` implementation.

**Pull request merged**
